# top level stuff you probably don't need to touch
markdown: kramdown
# highlighter: rouge 
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
permalink: pretty 
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: kotas.tech
title: Petr Kotas
author: Petr Kotas
description: Personal blog and ego boosting web
avatar: profile.png
email: petr.kotas@gmail.com
github: petrkotas 
twitter: petrkotas
linkedin: petrkotas

# needed for travis-ci build
exclude: [vendor]

# store site content in one place
# collections_dir: blog 

collections:
  projects:
    output: true
    permalink: /:collection/:title

include:
  - _pages
